repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of file
      - id: check-yaml
        name: Check YAML syntax
        exclude: ^templates/
      - id: check-json
        name: Check JSON syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ["--maxkb=1000"]

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        name: Helm docs
        description: Generate Helm chart documentation from templates
        entry: helm-docs
        language: golang
        files: ^(Chart\.yaml|values\.yaml|README\.md\.gotmpl|templates/.*\.(yaml|yml))$
        pass_filenames: false
        # always_run: true
        args:
          - --chart-search-root=.
          - --sort-values-order=file
          - --template-files=README.md.gotmpl
