{{- if $.Values.https.redirect -}}
apiVersion: "traefik.io/v1alpha1"
kind: "Middleware"
metadata:
  name: "redirect-https-{{ include "fullname" $ }}"
  {{- include "annotations" $ | indent 2 }}
  {{- include "labels" $ | indent 2 }}
spec:
  redirectScheme:
    scheme: https
    permanent: false
    port: "443"
{{- end -}}
